[package]
name = "unsafe-rust-testing-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.unsafe-rust-testing]
path = ".."

[[bin]]
name = "read_heap_rust"
path = "fuzz_targets/read_heap_rust.rs"
test = false
doc = false
bench = false

[[bin]]
name = "read_heap_c"
path = "fuzz_targets/read_heap_c.rs"
test = false
doc = false
bench = false

[[bin]]
name = "read_stack_rust"
path = "fuzz_targets/read_stack_rust.rs"
test = false
doc = false
bench = false

[[bin]]
name = "read_stack_c"
path = "fuzz_targets/read_stack_c.rs"
test = false
doc = false
bench = false

[[bin]]
name = "write_heap_rust"
path = "fuzz_targets/write_heap_rust.rs"
test = false
doc = false
bench = false

[[bin]]
name = "write_heap_c"
path = "fuzz_targets/write_heap_c.rs"
test = false
doc = false
bench = false


[[bin]]
name = "write_stack_rust"
path = "fuzz_targets/write_stack_rust.rs"
test = false
doc = false
bench = false

[[bin]]
name = "write_stack_c"
path = "fuzz_targets/write_stack_c.rs"
test = false
doc = false
bench = false
